repos:
- repo: local
  hooks:
    - id: custom-ruff-lint-check
      name: Validate all commited code pass linting rules.
      entry: uv run ruff check --force-exclude
      language: python
      types_or: [python, pyi]
      args: []
      require_serial: true
      additional_dependencies: []
      minimum_pre_commit_version: "2.9.2"
    
    - id: custom-ruff-reformatting
      name: Apply reFormat on all python files to keep them standard.
      entry: uv run ruff format --force-exclude
      language: python
      types_or: [python, pyi]
      args: []
      require_serial: true
      additional_dependencies: []
      minimum_pre_commit_version: "2.9.2"

